# Generated by Django 2.2.3 on 2019-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190724_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contry',
            field=models.CharField(default=('chennai', 'India'), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='chennai', max_length=40),
            preserve_default=False,
        ),
    ]
