# Generated by Django 2.2.3 on 2019-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190724_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dno',
            field=models.CharField(default=-52, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(default="NGO's Colony", max_length=30),
            preserve_default=False,
        ),
    ]
