# Generated by Django 2.2.3 on 2019-07-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190724_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dno',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='street',
        ),
    ]
